data:
  alt: 'Eine Gruppe von 8 Menschen sitzt im Innenhof zusammen. Sie sind Teil eines Workshops und arbeiten an Ideen.'
  focus: 46-75-1
size: 2264712
last_modified: 1756750942
width: 7581
height: 5057
mime_type: image/jpeg
duration: null
